config/routes.rb
ServidorActi::Application.routes.draw do
  resources :registros

  resources :cuentas

  resources :aplicaciones

  resources :usuarios
  
  resources :sesiones, only: [:new, :create, :destroy]
  
  match '/signin', to: 'sesiones#new' #Login html
  match '/login', to: 'sesiones#create' #Para hacer login desde Ext
  match '/signout', to: 'sesiones#destroy', via: :delete
  
  match '/activar', to: 'cuentas#activar'
  match '/desactivar', to: 'cuentas#desactivar'
  match '/informacion', to: 'cuentas#informacion'

 root :to => 'cuentas#index'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :correo, :nombre, :password, :password_confirmation

  has_secure_password
  before_save { |user| user.correo = correo.downcase }
  before_save :create_remember_token
  
  VALID_PASSWORD_REGEX = /[a-zA-Z][a-zA-Z0-9]{7,}/
  validates :password, presence: true, length: { minimum: 8 }, format: { with: VALID_PASSWORD_REGEX}
  validates :password_confirmation, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :correo, presence:  true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_filter :signed_in_usuario
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<div class = "row">
	<div class="span6 offset3">
		<%= form_for(@usuario) do |f| %>
		<% if @usuario.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

			<ul>
				<% @usuario.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="field">
			<%= f.label :nombre %>
			<br />
			<%= f.text_field :nombre %>
		</div>
		<div class="field">
			<%= f.label :correo %>
			<br />
			<%= f.text_field :correo %>
		</div>
		<div class="field">
			<%= f.label :password %>
			<br />
			<%= f.text_field :password %>
		</div>

		<div class="field">
			<%= f.label :password_confirmation %>
			<br />
			<%= f.text_field :password_confirmation %>
		</div>

		<div class="actions">
			<%= f.submit "Aceptar", class: "btn btn-small btn-primary" %>
		</div>
		<% end %>
	</div>
</div>

app/views/usuarios/edit.html.erb
<h1>Editar usuario</h1>

<%= render 'form' %>
<div class="row">
	<div class="span6 offset3">
		<%= link_to 'Ver', @usuario, class:"btn btn-small btn-primary" %> |
		<%= link_to 'Atrás', usuarios_path, class:"btn btn-small btn-primary" %>
	</div>
</div>

app/views/usuarios/index.html.erb
<h1>Listado de Usuarios</h1>

<div class="row-fluid">
	<div class="span12">
<table class="table table-striped">
	<thead>
  <tr>
    <th>Nombre</th>
    <th>Correo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
	<tbody>
<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.nombre %></td>
    <td><%= usuario.correo %></td>
    <td><%= link_to 'Ver', usuario, class: "btn" %></td>
    <td><%= link_to 'Editar', edit_usuario_path(usuario), class: "btn" %></td>
    <td><%= link_to 'Eliminar', usuario, confirm: 'Segurito segurito?', method: :delete, class: "btn btn-danger" %></td>
  </tr>
<% end %>
</tbody>
</table>
	</div>
</div>
<br />
<div class="row-fluid">
	<div class="span12">

<%= link_to 'Nuevo Usuario', new_usuario_path, class:"btn btn-small btn-primary" %>
	</div>
</div>

app/views/usuarios/new.html.erb
<h1>Nuevo usuario</h1>

<%= render 'form' %>
<div class="row">
	<div class="span6 offset3">
		<%= link_to 'Atrás', usuarios_path, class:"btn btn-small btn-primary" %>
	</div>
</div>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @usuario.nombre %>
</p>

<p>
  <b>Correo:</b>
  <%= @usuario.correo %>
</p>



<%= link_to 'Editar', edit_usuario_path(@usuario), class:"btn btn-small btn-primary" %> |
<%= link_to 'Atrás', usuarios_path, class:"btn btn-small btn-primary" %>