config/routes.rb
ServidorActi::Application.routes.draw do
  resources :registros

  resources :cuentas

  resources :aplicaciones

  resources :usuarios
  
  resources :sesiones, only: [:new, :create, :destroy]
  
  match '/signin', to: 'sesiones#new' #Login html
  match '/login', to: 'sesiones#create' #Para hacer login desde Ext
  match '/signout', to: 'sesiones#destroy', via: :delete
  
  match '/activar', to: 'cuentas#activar'
  match '/desactivar', to: 'cuentas#desactivar'
  match '/informacion', to: 'cuentas#informacion'

 root :to => 'cuentas#index'

end

app/models/cuenta.rb
class Cuenta < ActiveRecord::Base
  attr_accessible :aplicacion_id, :correo, :pendiente, :total
  belongs_to :aplicacion
  has_many :registros
end

app/controllers/cuentas_controller.rb
class CuentasController < ApplicationController
  before_filter :signed_in_usuario, only: [:index, :create, :show, :new, :update, :edit, :destroy]
  # GET /cuentas
  # GET /cuentas.json
  def index
    @cuentas = Cuenta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cuentas }
    end
  end

  # GET /cuentas/1
  # GET /cuentas/1.json
  def show
    @cuenta = Cuenta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cuenta }
    end
  end

  # GET /cuentas/new
  # GET /cuentas/new.json
  def new
    @cuenta = Cuenta.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cuenta }
    end
  end

  # GET /cuentas/1/edit
  def edit
    @cuenta = Cuenta.find(params[:id])
  end

  # POST /cuentas
  # POST /cuentas.json
  def create
    @cuenta = Cuenta.new(params[:cuenta])

    respond_to do |format|
      if @cuenta.save
        format.html { redirect_to @cuenta, notice: 'Cuenta was successfully created.' }
        format.json { render json: @cuenta, status: :created, location: @cuenta }
      else
        format.html { render action: "new" }
        format.json { render json: @cuenta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cuentas/1
  # PUT /cuentas/1.json
  def update
    @cuenta = Cuenta.find(params[:id])

    respond_to do |format|
      if @cuenta.update_attributes(params[:cuenta])
        format.html { redirect_to @cuenta, notice: 'Cuenta was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cuenta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuentas/1
  # DELETE /cuentas/1.json
  def destroy
    @cuenta = Cuenta.find(params[:id])
    @cuenta.destroy

    respond_to do |format|
      format.html { redirect_to cuentas_url }
      format.json { head :no_content }
    end
  end
  
  
  def informacion
    @cuenta = Cuenta.where(correo: params[:correo], aplicacion_id: params[:aplicacion_id]).first
    respond_to do |format|
      format.xml {render 'activar'}
    end
  end
  
  def activar
    @cuenta = Cuenta.where(correo: params[:correo], aplicacion_id: params[:aplicacion_id]).first
    if @cuenta
      if @cuenta.pendiente > 0
        @cuenta.pendiente = @cuenta.pendiente - 1
        if @cuenta.save
          Registro.create(cuenta_id: @cuenta.id, hora: DateTime.now(), pendiente: @cuenta.pendiente, total: @cuenta.total)
        end
      else
        @cuenta = nil
      end
    end
    respond_to do |format|
      format.xml #activar.xml.builder
    end
  end
  
  def desactivar
    @cuenta = Cuenta.where(correo: params[:correo], aplicacion_id: params[:aplicacion_id]).first
     if @cuenta
      if @cuenta.pendiente < @cuenta.total
        @cuenta.pendiente = @cuenta.pendiente + 1
        if @cuenta.save
          Registro.create(cuenta_id: @cuenta.id, hora: DateTime.now(), pendiente: @cuenta.pendiente, total: @cuenta.total)
        end
      else
        @cuenta = nil
      end
    end
    respond_to do |format|
      format.xml {render 'activar'}
    end
  end
end

app/helpers/cuentas_helper.rb
module CuentasHelper
end

app/views/cuentas/_form.html.erb
<div class = "row">
	<div class="span6 offset3">
		<%= form_for(@cuenta) do |f| %>
		<% if @cuenta.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@cuenta.errors.count, "error") %> prohibited this cuenta from being saved:</h2>

			<ul>
				<% @cuenta.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="field">
			<%= f.label :correo %>
			<br />
			<%= f.text_field :correo %>
		</div>
		<div class="field">
			<%= f.label :pendiente %>
			<br />
			<%= f.number_field :pendiente %>
		</div>
		<div class="field">
			<%= f.label :total %>
			<br />
			<%= f.number_field :total %>
		</div>
		<div class="field">
			<%= f.label :aplicacion_id %>
			<br />
			<%= collection_select(:cuenta,:aplicacion_id, Aplicacion.all, :id, :nombre) %>
		</div>
		<div class="actions">
			<%= f.submit "Aceptar", class: "btn btn-small btn-primary" %>
		</div>
		<% end %>
	</div>
</div>

app/views/cuentas/edit.html.erb
<h1>Editar cuenta</h1>

<%= render 'form' %>
<div class="row">
	<div class="span6 offset3">
<%= link_to 'Ver', @cuenta, class:"btn btn-small btn-primary" %> |
<%= link_to 'Atrás', cuentas_path, class:"btn btn-small btn-primary" %>
</div>
</div>

app/views/cuentas/index.html.erb
<h1>Listado de Cuentas</h1>
<div class="row-fluid">
	<div class="span12">
<table class="table table-striped">
	<thead>
		<tr>
			<th>Correo</th>
			<th>Pendiente</th>
			<th>Total</th>
			<th>Aplicación</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @cuentas.each do |cuenta| %>
		<tr>
			<td><%= cuenta.correo %></td>
			<td><%= cuenta.pendiente %></td>
			<td><%= cuenta.total %></td>
			<td><%= cuenta.aplicacion.nombre %></td>
			<td><%= link_to 'Ver', cuenta, class: "btn" %></td>
			<td><%= link_to 'Editar', edit_cuenta_path(cuenta), class: "btn" %></td>
			<td><%= link_to 'Eliminar', cuenta, confirm: 'Segurito segurito?', method: :delete, class: "btn btn-danger" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
	</div>
</div>
<br />
<div class="row-fluid">
	<div class="span12">

		<%= link_to 'Nueva Cuenta', new_cuenta_path, class:"btn btn-small btn-primary" %>
	</div>
</div>

app/views/cuentas/new.html.erb
<h1>Nueva cuenta</h1>

<%= render 'form' %>
<div class="row">
	<div class="span6 offset3">
<%= link_to 'Atrás', cuentas_path, class:"btn btn-small btn-primary" %>
</div>
</div>

app/views/cuentas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Correo:</b>
  <%= @cuenta.correo %>
</p>

<p>
  <b>Pendiente:</b>
  <%= @cuenta.pendiente %>
</p>

<p>
  <b>Total:</b>
  <%= @cuenta.total %>
</p>

<p>
  <b>Aplicacion:</b>
  <%= @cuenta.aplicacion.nombre %>
</p>


<%= link_to 'Editar', edit_cuenta_path(@cuenta), class:"btn btn-small btn-primary" %> |
<%= link_to 'Atrás', cuentas_path, class:"btn btn-small btn-primary" %>