config/routes.rb
ServidorActi::Application.routes.draw do
  resources :registros

  resources :cuentas

  resources :aplicaciones

  resources :usuarios
  
  resources :sesiones, only: [:new, :create, :destroy]
  
  match '/signin', to: 'sesiones#new' #Login html
  match '/login', to: 'sesiones#create' #Para hacer login desde Ext
  match '/signout', to: 'sesiones#destroy', via: :delete
  
  match '/activar', to: 'cuentas#activar'
  match '/desactivar', to: 'cuentas#desactivar'
  match '/informacion', to: 'cuentas#informacion'

 root :to => 'cuentas#index'

end

app/models/registro.rb
class Registro < ActiveRecord::Base
  attr_accessible :cuenta_id, :hora, :pendiente, :total
  belongs_to :cuenta
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_filter :signed_in_usuario
  # GET /registros
  # GET /registros.json
  def index
    @registros = Registro.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @registros }
    end
  end

  # GET /registros/1
  # GET /registros/1.json
  def show
    @registro = Registro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @registro }
    end
  end

  # GET /registros/new
  # GET /registros/new.json
  def new
    @registro = Registro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @registro }
    end
  end

  # GET /registros/1/edit
  def edit
    @registro = Registro.find(params[:id])
  end

  # POST /registros
  # POST /registros.json
  def create
    @registro = Registro.new(params[:registro])

    respond_to do |format|
      if @registro.save
        format.html { redirect_to @registro, notice: 'Registro was successfully created.' }
        format.json { render json: @registro, status: :created, location: @registro }
      else
        format.html { render action: "new" }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /registros/1
  # PUT /registros/1.json
  def update
    @registro = Registro.find(params[:id])

    respond_to do |format|
      if @registro.update_attributes(params[:registro])
        format.html { redirect_to @registro, notice: 'Registro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registros/1
  # DELETE /registros/1.json
  def destroy
    @registro = Registro.find(params[:id])
    @registro.destroy

    respond_to do |format|
      format.html { redirect_to registros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/views/registros/_form.html.erb
<div class = "row">
	<div class="span6 offset3">
		<%= form_for(@registro) do |f| %>
		<% if @registro.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@registro.errors.count, "error") %> prohibited this registro from being saved:</h2>

			<ul>
				<% @registro.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="field">
			<%= f.label :cuenta_id %>
			<br />
			<% opciones = Cuenta.all.map { |cuenta| ["#{cuenta.correo} | #{cuenta.aplicacion.nombre}", cuenta.id] }%>
			<%= f.select(:cuenta_id, options_for_select(opciones)) %>
		</div>
		<div class="field">
			<%= f.label :hora %>
			<br />
			<%= f.datetime_select :hora %>
		</div>
		<div class="field">
			<%= f.label :pendiente %>
			<br />
			<%= f.number_field :pendiente %>
		</div>
		<div class="field">
			<%= f.label :total %>
			<br />
			<%= f.number_field :total %>
		</div>
		<div class="actions">
			<%= f.submit "Aceptar", class: "btn btn-small btn-primary" %>
		</div>
		<% end %>
	</div>
</div>

app/views/registros/edit.html.erb
<h1>Editar registro</h1>

<%= render 'form' %>
<div class="row">
	<div class="span6 offset3">
<%= link_to 'Ver', @registro, class:"btn btn-small btn-primary" %> |
<%= link_to 'Atrás', registros_path, class:"btn btn-small btn-primary" %>
</div>
</div>

app/views/registros/index.html.erb
<h1>Registro de actividades</h1>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Cuenta</th>
					<th>Hora</th>
					<th>Pendiente</th>
					<th>Total</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @registros.each do |registro| %>
				<tr>
					<td><%= registro.cuenta.correo %></td>
					<td><%= registro.hora %></td>
					<td><%= registro.pendiente %></td>
					<td><%= registro.total %></td>
					<td><%= link_to 'Ver', registro,class: "btn" %></td>
					<td><%= link_to 'Editar', edit_registro_path(registro), class: "btn" %></td>
					<td><%= link_to 'Eliminar', registro, confirm: 'Segurito segurito?', method: :delete, class: "btn btn-danger" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<br />
<div class="row-fluid">
	<div class="span12">

		<%= link_to 'Nueva entrada de registro', new_registro_path, class:"btn btn-small btn-primary" %>

	</div>
</div>

app/views/registros/new.html.erb
<h1>Nuevo registro</h1>

<%= render 'form' %>
<div class="row">
	<div class="span6 offset3">
<%= link_to 'Back', registros_path, class:"btn btn-small btn-primary" %>
</div>
</div>

app/views/registros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cuenta:</b>
  <%= @registro.cuenta.correo %>
</p>

<p>
  <b>Hora:</b>
  <%= @registro.hora %>
</p>

<p>
  <b>Pendiente:</b>
  <%= @registro.pendiente %>
</p>

<p>
  <b>Total:</b>
  <%= @registro.total %>
</p>


<%= link_to 'Editar', edit_registro_path(@registro), class:"btn btn-small btn-primary" %> |
<%= link_to 'Atrás', registros_path, class:"btn btn-small btn-primary" %>