config/routes.rb
ServidorActi::Application.routes.draw do
  resources :registros

  resources :cuentas

  resources :aplicaciones

  resources :usuarios
  
  resources :sesiones, only: [:new, :create, :destroy]
  
  match '/signin', to: 'sesiones#new' #Login html
  match '/login', to: 'sesiones#create' #Para hacer login desde Ext
  match '/signout', to: 'sesiones#destroy', via: :delete
  
  match '/activar', to: 'cuentas#activar'
  match '/desactivar', to: 'cuentas#desactivar'
  match '/informacion', to: 'cuentas#informacion'

 root :to => 'cuentas#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Servidor Activación ehmSoftware</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header class="navbar navbar-inverse">
			<div class="navbar-inner">			
				<div class="container-fluid">
					<nav>
						<ul class="nav">
							<li><%= image_tag("logo.png", alt: "ehmSoftware Logo") %></li>
							<li>
								<%= link_to "Cuentas", cuentas_path, id: "navlink" %>
							</li>
							<li>
								<%= link_to "Usuarios", usuarios_path, id: "navlink" %>
							</li>
							
							<li>
								<%= link_to "Aplicaciones", aplicaciones_path, id: "navlink" %>
							</li>
							
							<li>
								<%= link_to "Registro Actividades", registros_path, id: "navlink" %>
							</li>
							
							<% if signed_in? %>
							<li>
								<%= link_to "Cerrar sesión", signout_path, method: "delete", id: "navlink" %>
							</li>

							<% end %>
						</ul>
					</nav>
				</div>
			</div>
		</header>

		<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>">
			<%= value %>
		</div>
		<% end %>
		<%= yield %>

	</body>
</html>